<?php

namespace ContainerKJorJxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L5jQlR_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L5jQlR.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L5jQlR.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.G62_GBc', 'get_ServiceLocator_G62GBcService', true],
            'App\\Controller\\MainController::rentProduct' => ['privates', '.service_locator.DBJKCeA', 'get_ServiceLocator_DBJKCeAService', true],
            'App\\Controller\\MainController::returnProduct' => ['privates', '.service_locator.DBJKCeA', 'get_ServiceLocator_DBJKCeAService', true],
            'App\\Controller\\MainController::showCriteria' => ['privates', '.service_locator.2RmIwlS', 'get_ServiceLocator_2RmIwlSService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.fd.UL7I', 'get_ServiceLocator_Fd_UL7IService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.G62_GBc', 'get_ServiceLocator_G62GBcService', true],
            'App\\Controller\\MainController:rentProduct' => ['privates', '.service_locator.DBJKCeA', 'get_ServiceLocator_DBJKCeAService', true],
            'App\\Controller\\MainController:returnProduct' => ['privates', '.service_locator.DBJKCeA', 'get_ServiceLocator_DBJKCeAService', true],
            'App\\Controller\\MainController:showCriteria' => ['privates', '.service_locator.2RmIwlS', 'get_ServiceLocator_2RmIwlSService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.fd.UL7I', 'get_ServiceLocator_Fd_UL7IService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\MainController::rentProduct' => '?',
            'App\\Controller\\MainController::returnProduct' => '?',
            'App\\Controller\\MainController::showCriteria' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\MainController:rentProduct' => '?',
            'App\\Controller\\MainController:returnProduct' => '?',
            'App\\Controller\\MainController:showCriteria' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
