<?php

namespace Container4Ps0Mqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HPyV8QiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hPyV8Qi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hPyV8Qi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repos' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'repos' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
