<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIJua1Tr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIJua1Tr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIJua1Tr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIJua1Tr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIJua1Tr\App_KernelDevDebugContainer([
    'container.build_hash' => 'IJua1Tr',
    'container.build_id' => '168f63c9',
    'container.build_time' => 1613485549,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIJua1Tr');
