<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4MUpzfR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4MUpzfR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4MUpzfR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4MUpzfR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4MUpzfR\App_KernelDevDebugContainer([
    'container.build_hash' => '4MUpzfR',
    'container.build_id' => '69f6efb4',
    'container.build_time' => 1613687092,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4MUpzfR');
