<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerViqNTDl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerViqNTDl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerViqNTDl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerViqNTDl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerViqNTDl\App_KernelDevDebugContainer([
    'container.build_hash' => 'ViqNTDl',
    'container.build_id' => '0855337a',
    'container.build_time' => 1614442810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerViqNTDl');
